const ROLE = Object.freeze({
  ADMIN: 'ADMIN',
  MOZO: 'MOZO',
  COCINERO: 'COCINERO',
  CAJERO: 'CAJERO',
  DELIVERY: 'DELIVERY'
});

const CAPABILITY = Object.freeze({
  ADMIN_ONLY: 'ADMIN_ONLY',
  CASH_MANAGEMENT: 'CASH_MANAGEMENT',
  TABLES_ACCESS: 'TABLES_ACCESS',
  ORDERS_LIST: 'ORDERS_LIST',
  ORDERS_CREATE: 'ORDERS_CREATE',
  ORDERS_UPDATE_STATUS: 'ORDERS_UPDATE_STATUS',
  ORDERS_CANCEL: 'ORDERS_CANCEL',
  KITCHEN_ACCESS: 'KITCHEN_ACCESS',
  DELIVERY_ACCESS: 'DELIVERY_ACCESS',
  PAYMENT_REGISTER: 'PAYMENT_REGISTER',
  DASHBOARD_VIEW: 'DASHBOARD_VIEW',
  REPORTS_VIEW: 'REPORTS_VIEW',
  REPORTS_ADVANCED: 'REPORTS_ADVANCED',
  SETTINGS_MANAGE: 'SETTINGS_MANAGE',
  SUBSCRIPTION_MANAGE: 'SUBSCRIPTION_MANAGE',
  MERCADOPAGO_MANAGE: 'MERCADOPAGO_MANAGE'
});

const CAPABILITY_ROLES = Object.freeze({
  [CAPABILITY.ADMIN_ONLY]: [ROLE.ADMIN],
  [CAPABILITY.CASH_MANAGEMENT]: [ROLE.ADMIN, ROLE.CAJERO],
  [CAPABILITY.TABLES_ACCESS]: [ROLE.ADMIN, ROLE.MOZO],
  [CAPABILITY.ORDERS_LIST]: [ROLE.ADMIN, ROLE.MOZO, ROLE.CAJERO],
  [CAPABILITY.ORDERS_CREATE]: [ROLE.ADMIN, ROLE.MOZO, ROLE.CAJERO],
  [CAPABILITY.ORDERS_UPDATE_STATUS]: [ROLE.ADMIN, ROLE.COCINERO, ROLE.MOZO],
  [CAPABILITY.ORDERS_CANCEL]: [ROLE.ADMIN, ROLE.CAJERO],
  [CAPABILITY.KITCHEN_ACCESS]: [ROLE.ADMIN, ROLE.COCINERO],
  [CAPABILITY.DELIVERY_ACCESS]: [ROLE.ADMIN, ROLE.DELIVERY],
  [CAPABILITY.PAYMENT_REGISTER]: [ROLE.ADMIN, ROLE.CAJERO],
  [CAPABILITY.DASHBOARD_VIEW]: [ROLE.ADMIN, ROLE.COCINERO, ROLE.CAJERO],
  [CAPABILITY.REPORTS_VIEW]: [ROLE.ADMIN, ROLE.CAJERO],
  [CAPABILITY.REPORTS_ADVANCED]: [ROLE.ADMIN],
  [CAPABILITY.SETTINGS_MANAGE]: [ROLE.ADMIN],
  [CAPABILITY.SUBSCRIPTION_MANAGE]: [ROLE.ADMIN],
  [CAPABILITY.MERCADOPAGO_MANAGE]: [ROLE.ADMIN]
});

const rolesForCapability = (capability) => CAPABILITY_ROLES[capability] || [];

const hasRoleForCapability = (role, capability) =>
  rolesForCapability(capability).includes(role);

module.exports = {
  ROLE,
  CAPABILITY,
  CAPABILITY_ROLES,
  rolesForCapability,
  hasRoleForCapability
};
